0, 
滨海湾金沙酒店与金沙空中花园
  
, page: None, 2020-01-31 16:35:11.924972
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 172, in crawl_pois
    self.crawl_reviews()
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 312, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 416, in crawl_reviews_1_page
    raise Exception("random clicking happened")
Exception: random clicking happened

1, 
圣淘沙岛
  
, page: None, 2020-01-31 16:35:45.304854
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 172, in crawl_pois
    self.crawl_reviews()
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 312, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 416, in crawl_reviews_1_page
    raise Exception("random clicking happened")
Exception: random clicking happened

2, 
新加坡环球影城
  
, page: None, 2020-01-31 16:36:21.318833
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 172, in crawl_pois
    self.crawl_reviews()
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 312, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 416, in crawl_reviews_1_page
    raise Exception("random clicking happened")
Exception: random clicking happened

2, 
新加坡环球影城
  
, page: None, 2020-01-31 16:36:36.277547
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 172, in crawl_pois
    self.crawl_reviews()
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 312, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 412, in crawl_reviews_1_page
    self.sel = Selector(text=self.driver.page_source)
  File "/home/jia/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/home/jia/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jia/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=79.0.3945.130)


