0, 
滨海湾金沙酒店与金沙空中花园
  
, page: None, 2020-02-05 10:12:21.252311
Traceback (most recent call last):
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 160, in crawl_pois
    self.crawl_reviews()
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 320, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 400, in crawl_reviews_1_page
    sleep(1+random()*2)
KeyboardInterrupt

0, 
滨海湾金沙酒店与金沙空中花园
  
, page: None, 2020-02-05 10:12:48.938423
Traceback (most recent call last):
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 160, in crawl_pois
    self.crawl_reviews()
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 320, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 401, in crawl_reviews_1_page
    self.sel = Selector(text=self.driver.page_source)
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=78.0.3904.87)


0, 
滨海湾金沙酒店与金沙空中花园
  
, page: None, 2020-02-05 10:13:03.382066
Traceback (most recent call last):
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 160, in crawl_pois
    self.crawl_reviews()
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 320, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 394, in crawl_reviews_1_page
    next_page_button = self.driver.find_elements_by_xpath('//a[@title="下一页"]')
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 410, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=78.0.3904.87)


0, 
滨海湾金沙酒店与金沙空中花园
  
, page: None, 2020-02-05 10:13:51.219552
Traceback (most recent call last):
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 160, in crawl_pois
    self.crawl_reviews()
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 320, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/jirong/Desktop/stb_crawl/STB_social_media_analytics/experimentation/jiaxin_experiment/QY/QY_crawler.py", line 401, in crawl_reviews_1_page
    self.sel = Selector(text=self.driver.page_source)
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jirong/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=78.0.3904.87)


