1, Gardens by the Bay, page: 1916, 2020-01-22 03:19:05.626189
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/crawl_TripA_POI_attributes_reviews.py", line 198, in crawl_reviews_1_page
    read_more_button.click()
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=79.0.3945.130)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/crawl_TripA_POI_attributes_reviews.py", line 93, in crawl_pois
    self.crawl_reviews(row['poi_index'])
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/crawl_TripA_POI_attributes_reviews.py", line 110, in crawl_reviews
    self.crawl_reviews_1_page(poi_index)
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/crawl_TripA_POI_attributes_reviews.py", line 203, in crawl_reviews_1_page
    read_more_button.click()
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=79.0.3945.130)


