Error in API call.
POI index: 50, review ID: 691737417, row index: 0, time: 2020-02-10 13:23:16.648558
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 185, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 245, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 0 exhausted.

Error in API call.
POI index: 50, review ID: 691737417, row index: 0, time: 2020-02-10 13:23:17.956576
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 185, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 245, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 1 exhausted.

Error in API call.
POI index: 50, review ID: 691737417, row index: 0, time: 2020-02-10 13:23:19.692290
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 185, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 245, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 2 exhausted.

Error in API call.
POI index: 50, review ID: 691737417, row index: 0, time: 2020-02-10 13:23:20.757537
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 185, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 245, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

API key 3 exhausted.

Error in API call.
POI index: 58, review ID: 555135882, row index: 995, time: 2020-02-10 14:11:41.957050
Traceback (most recent call last):
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 185, in score_sentiments_1_poi
    self.get_api_response()
  File "/home/zyf0717/git/STB_social_media_analytics/tripadvisor/sentiment_scorer.py", line 245, in get_api_response
    keywords=KeywordsOptions(emotion=True, sentiment=True, limit=10000)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py", line 186, in analyze
    response = self.send(request)
  File "/home/zyf0717/anaconda3/envs/crawl/lib/python3.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 157, in send
    response.status_code, error_message, http_response=response)
ibm_cloud_sdk_core.api_exception.ApiException: Error: unsupported text language: ar, Code: 400 , X-global-transaction-id: cdf0e849463c5b0cc6d5d2a221e7c2f1

