564, 千灯寺 , 2020-02-11 22:10:51.134674, current POI does not exist
564, 千灯寺 , page: 1, 2020-02-11 22:10:51.135250
Traceback (most recent call last):
  File "/home/jia/Desktop/git/STB_social_media_analytics/experimentation/jiaxin_experiment/ctrip/Ctrip_crawler.py", line 261, in crawl_pois
    raise Exception("current POI does not exist")
Exception: current POI does not exist

